config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
    @files = Dir.glob('*')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BYEtle page!</title>
</head>
<body>
  <h1>Goodbye!</h1>
</body>
<p>
  It is very pleasure that you visited us!
</p>
<p>
  To say <%= link_to "hello", say_hello_path %> one more time!
</p>
</html>




<p> <%= 1+2 %> </p>
<p> <%= "cow"+"boy" %> </p>
<p> <%= 1.hour.from_now %> </p>


<p>
<% for file in @files %>
<ul> file name is: <%= file %> </ul>
<% end %>
</p>

app/views/say/hello.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>title page!</title>
</head>
<body>
  <h1>Hello from Rails!</h1>
</body>
<p>
  It's <%= @time %> now
</p>
<p>
  Is was nice having you here!
</p>
<p>
  It is time to say
  <%= link_to "goodbye", say_goodbye_path %>!
</p>
</html>